### ISSUE TITLE
key_setup() - why extra shuffle?

### ISSUE THREAD

**Issue by ghost** [jedisct1/spritz#1]
Clarification please ...

static void key_setup(State *state, const unsigned char *key, size_t keylen)
{
    initialize_state(state);
    absorb(state, key, keylen);
    if (state->a > 0) {   //  <<<<<<<
        shuffle(state);   //  <<<<<<<
    }                           //  <<<<<<<
}

Why the additional shuffle step? It's not in the paper AFAIK, unless I missed something.

**Comment by jedisct1** [comment]
Correct. This has been removed in ad28049b18a9417e3e3f755d5201b4b0592c461b . Thanks!
